// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "api-campana",
    "version": "1"
  },
  "paths": {
    "/consultar-mensajes": {
      "post": {
        "summary": "consultarMensajes",
        "description": "",
        "operationId": "consultarMensajes.post./consultar-mensajes",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/crear-campana": {
      "post": {
        "summary": "crearCampana",
        "description": "",
        "operationId": "crearCampana.post./crear-campana",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {}
};